default_stages: [pre-commit]

repos:
  - repo: local
    hooks:
      - id: staged-diff-check
        name: staged diff check
        entry: git diff --cached --check
        language: system
        pass_filenames: false
